def test=new Test()
try{
  test.foo();
} catch (Exception e) {

}